Target blank was not respectged when clicking on a new link
tatewake/dokuwiki-plugin-googleanalytics pull request #16
Opened 2020-06-17 10:19 UTC by gerardnico

This the PR for the issue #15 

I have added an HTML test page.

2020-06-17 22:16 UTC, phy25 requested changes
I think it was there to make sure Google Analytics finishes the job before redirecting. We can either use a different way to record it or check the target value, but this is not the right way to fix it I guess.

2020-06-17 22:32 UTC, gerardnico commented
Ah yes you'r right. The original tab is also navigating. I will look into it later.

2020-06-23 11:08 UTC, gerardnico commented
The callback is not needed. I have improved the test html page where I have written all steps to validate it.
I have also added a debug mode that prints the hit payload to the console.
This version is already running at https://datacadamia.com

2020-06-23 23:12 UTC, phy25 commented
My bad. Looks like when this code is initially introduced, `transport: beacon` is already used, and thus there is no need to wait for the request to complete.

I would recommend reusing DokuWiki-wide `$conf['allowdebug']` for it as I don't think it needs a separate control.

2020-06-24 06:57 UTC, gerardnico commented
For what I see, they let just the default event takes place. They just record it. I have changed the local debug conf by the global one.

2020-06-26 03:38 UTC, phy25 commented
> they let just the default event takes place. They just record it

This is actually something called [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API) which does work even after users close the page. Note that it doesn't always work but it should be good enough.

2020-06-26 03:39 UTC, phy25 approved these changes

2020-06-26 03:39 UTC, phy25 commented on lang/en/settings.php
> +$lang['debug'] = 'Debug mode: Send the hits to the console';
This line is not needed anymore.

```suggestion
```

2020-06-26 03:51 UTC, tatewake approved these changes

2020-06-26 03:53 UTC, tatewake commented
Hi @gerardnico and @phy25 , thank you for your changes and feedback.
Everything looks good here and I'll go ahead and prepare a new version release for the plugin.

2020-06-26 03:58 UTC, merged

2020-06-26 05:46 UTC, tatewake commented
Hello; your changes have now been merged into master and there is a new release available if you wish to upgrade via the DokuWiki extension manager. Thanks again for your changes!

2020-06-27 20:13 UTC, gerardnico commented
I have a little bit difficulty to follow the thread as I'm not used to github. The fact that you got a discussion on a PR and on an issue
is a little bit disturbing. Thanks for the feedback !